---
title: "Board Exchange Stats, Models - Party Cycle"
author: "Joshua G. Mausolf"
date: "1/23/2020"
output:
  pdf_document: default
  htmcl_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, message=FALSE, warning=FALSE)
```



```{r loadsources, echo=FALSE}
source("analysis_source_cycle.R")

######################################
## Load Libraries & Data
######################################


library(Rmisc)
library(Hmisc)
library(tidyverse)
library(bbplot)
library(scales)
library(RColorBrewer)
library(ggthemes)
library(lme4)
library(car)




#Overwrite bbplot finalise_plot() function
source("bb_finalise_plot_academic.R")


dfb <- dfb %>% 
  filter(new_bm_party != "UNK") %>% 
  mutate(lnyear = log(year)) %>% 
  mutate(ticker_id = as.numeric(factor(ticker))) %>%
  mutate(lnticker = log(ticker_id)) %>% 
  mutate(lnage_med = log(age_median)) %>% 
  mutate(lnboard_size = log(board_size)) %>% 
  mutate(sector2 = fct_recode(sector,
    "Other"   = "Conglomerates",
    "Other"   = "Consumer Goods")) %>% 
  mutate(sector2 = factor(sector2)) %>% 
  mutate(fec_cluster_party = factor(fec_cluster_party)) %>% 
  mutate(bp_pid2n_median = factor(bp_pid2n_median)) %>% 
  mutate(who_pres = factor(who_pres)) %>% 
  mutate(who_becomes_pres = factor(who_becomes_pres))

table(dfb$bp_pid2n_median)
table(dfb$new_bm_party_rep)

table(dfb$party_var)
```



```{r}
df <- dfb %>%
  filter(lag_years == 1)



mc1r <- glm(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median, 
              data = df, family = binomial(link = "logit"))



mc2r <- glm(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                relevel(who_pres, ref = "REP"),
              data = df, family = binomial(link = "logit"))


mc3r <- glm(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                sector +
                relevel(who_pres, ref = "REP"),
              data = df, family = binomial(link = "logit"))


df <- dfb %>%
  filter(lag_years >= 1) 

mc4r <- glm(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector + 
                lag_years +
                relevel(who_pres, ref = "REP"),
              data = df, family = binomial(link = "logit"))


models <- list(mc1r, mc2r, mc3r, mc4r)

stargazer2(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```







```{r}
df <- dfb %>%
  filter(lag_years == 1) 


mc1d <- glm(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median, 
              data = df, family = binomial(link = "logit"))



mc2d <- glm(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                relevel(who_pres, ref = "REP"),
              data = df, family = binomial(link = "logit"))




mc3d <- glm(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                sector +
                relevel(who_pres, ref = "REP"),
              data = df, family = binomial(link = "logit"))


df <- dfb %>%
  filter(lag_years >= 1) 

mc4d <- glm(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector + 
                lag_years +
                relevel(who_pres, ref = "REP"),
              data = df, family = binomial(link = "logit"))


models <- list(mc1d, mc2d, mc3d, mc4d)

stargazer2(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```



# GLMER Models Full


```{r glmermodels_replag1}

df <- dfb %>%
  filter(lag_years == 1) 


mc1lr <- glmer(new_bm_party_rep ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mc1lr)
vif(mc1lr)

mc2lr <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc2lr)
vif(mc2lr)

mc3lr <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc3lr)
vif(mc3lr)

mc4lr <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc4lr)
vif(mc4lr)


models <- list(mc1lr, mc2lr, mc3lr, mc4lr)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```

```{r glmermodels_demclag1}

df <- dfb %>%
  filter(lag_years == 1) 


mc1ld <- glmer(new_bm_party_dem ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mc1ld)
vif(mc1ld)

mc2ld <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc2ld)
vif(mc2ld)

mc3ld <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc3ld)
vif(mc3ld)

mc4ld <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc4ld)
vif(mc4ld)


models <- list(mc1ld, mc2ld, mc3ld, mc4ld)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```

```{r glmermodels_replag2}

df <- dfb %>%
  filter(lag_years == 2) 


mc1lr2 <- glmer(new_bm_party_rep ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mc1lr2)
vif(mc1lr2)

mc2lr2 <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc2lr2)
vif(mc2lr2)

mc3lr2 <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc3lr2)
vif(mc3lr2)

mc4lr2 <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc4lr2)
vif(mc4lr2)

#models <- list(mc1lr, mc2lr, mc3lr, mc4lr)
models <- list(mc1lr2, mc2lr2, mc3lr2, mc4lr2)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```


```{r glmermodels_demclag2}

df <- dfb %>%
  filter(lag_years == 2) 


mc1ld2 <- glmer(new_bm_party_dem ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mc1ld2)
vif(mc1ld2)

mc2ld2 <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc2ld2)
vif(mc2ld2)

mc3ld2 <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc3ld2)
vif(mc3ld2)

mc4ld2 <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                relevel(who_pres, ref = "REP") +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc4ld2)
vif(mc4ld2)

models <- list(mc1ld2, mc2ld2, mc3ld2, mc4ld2)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```

#All Year Lag Models

```{r glmermodels_replag_all}

df <- dfb %>%
  filter(lag_years >= 1) 


mc1lr_all <- glmer(new_bm_party_rep ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mc1lr_all)
vif(mc1lr_all)

mc2lr_all <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc2lr_all)
vif(mc2lr_all)

mc3lr_all <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc3lr_all)
vif(mc3lr_all)

mc4lr_all <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc4lr_all)
vif(mc4lr_all)


models <- list(mc1lr_all, mc2lr_all, mc3lr_all, mc4lr_all)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```


```{r glmermodels_demclag_all}

df <- dfb %>%
  filter(lag_years >= 1) 


mc1ld_all <- glmer(new_bm_party_dem ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mc1ld_all)
vif(mc1ld_all)

mc2ld_all <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc2ld_all)
vif(mc2ld_all)

mc3ld_all <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc3ld_all)
vif(mc3ld_all)

mc4ld_all <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc4ld_all)
vif(mc4ld_all)

models <- list(mc1ld_all, mc2ld_all, mc3ld_all, mc4ld_all)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```

#All Year Lag Models (RepRef)

```{r glmermodels_replag_all_repref}

df <- dfb %>%
  filter(lag_years >= 1) 


mc1lr_all_repref <- glmer(new_bm_party_rep ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                relevel(bp_pid2n_median, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mc1lr_all_repref)
vif(mc1lr_all_repref)

mc2lr_all_repref <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                relevel(bp_pid2n_median, ref = "REP") + 
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc2lr_all_repref)
vif(mc2lr_all_repref)

mc3lr_all_repref <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                relevel(bp_pid2n_median, ref = "REP") + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc3lr_all_repref)
vif(mc3lr_all_repref)

mc4lr_all_repref <- glmer(new_bm_party_rep ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                relevel(bp_pid2n_median, ref = "REP") + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc4lr_all_repref)
vif(mc4lr_all_repref)


models <- list(mc1lr_all_repref, mc2lr_all_repref, mc3lr_all_repref, mc4lr_all_repref)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```


```{r glmermodels_demclag_all_repref}

df <- dfb %>%
  filter(lag_years >= 1) 


mc1ld_all_repref <- glmer(new_bm_party_dem ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                relevel(bp_pid2n_median, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mc1ld_all_repref)
vif(mc1ld_all_repref)

mc2ld_all_repref <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                relevel(bp_pid2n_median, ref = "REP") + 
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc2ld_all_repref)
vif(mc2ld_all_repref)

mc3ld_all_repref <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                relevel(bp_pid2n_median, ref = "REP") + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc3ld_all_repref)
vif(mc3ld_all_repref)

mc4ld_all_repref <- glmer(new_bm_party_dem ~ 
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                relevel(bp_pid2n_median, ref = "REP") + 
                relevel(fec_cluster_party, ref = "OTH") +
                lnboard_size +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                relevel(who_pres, ref = "REP") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(mc4ld_all_repref)
vif(mc4ld_all_repref)

models <- list(mc1ld_all_repref, mc2ld_all_repref, mc3ld_all_repref, mc4ld_all_repref)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```




#Tables of main coefficients, varying the number of included lag ranges


```{r multilagmodels_dem}

df <- dfb %>%
  filter(lag_years <= 2)


mcld_2 <- glmer(new_bm_party_dem ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                relevel(fec_cluster_party, ref = "OTH") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mcld_2)
vif(mcld_2)


df <- dfb %>%
  filter(lag_years <= 4)


mcld_4 <- glmer(new_bm_party_dem ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                relevel(fec_cluster_party, ref = "OTH") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mcld_4)
vif(mcld_4)


df <- dfb %>%
  filter(lag_years <= 6)

mcld_6 <- glmer(new_bm_party_dem ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                relevel(fec_cluster_party, ref = "OTH") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mcld_6)
vif(mcld_6)


df <- dfb %>%
  filter(lag_years <= 8)

mcld_8 <- glmer(new_bm_party_dem ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                relevel(fec_cluster_party, ref = "OTH") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mcld_8)
vif(mcld_8)


models <- list(mcld_2, mcld_4, mcld_6, mcld_8)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))
```


```{r multilagmodels_rep}

df <- dfb %>%
  filter(lag_years <= 2)


mclr_2 <- glmer(new_bm_party_rep ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                relevel(fec_cluster_party, ref = "OTH") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mclr_2)
vif(mclr_2)


df <- dfb %>%
  filter(lag_years <= 4)


mclr_4 <- glmer(new_bm_party_rep ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                relevel(fec_cluster_party, ref = "OTH") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mclr_4)
vif(mclr_4)


df <- dfb %>%
  filter(lag_years <= 6)

mclr_6 <- glmer(new_bm_party_rep ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                relevel(fec_cluster_party, ref = "OTH") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mclr_6)
vif(mclr_6)


df <- dfb %>%
  filter(lag_years <= 8)

mclr_8 <- glmer(new_bm_party_rep ~
                board_change_events_list_add +
                equal_swap_ep_party_yes +
                bp_pid2n_median +
                relevel(fec_cluster_party, ref = "OTH") +
                (1|lag_years) +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mclr_8)
vif(mclr_8)


models <- list(mclr_2, mclr_4, mclr_6, mclr_8)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))
```