---
title: "Board Exchange Stats, Models"
author: "Joshua G. Mausolf"
date: "1/23/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, message=FALSE, warning=FALSE)
```



```{r loadsources, echo=FALSE}
source("analysis_source.R")

######################################
## Load Libraries & Data
######################################


library(Rmisc)
library(Hmisc)
library(tidyverse)
library(bbplot)
library(scales)
library(RColorBrewer)
library(ggthemes)
library(lme4)
library(car)


colors_neutral = rev(brewer.pal(n = 8, name = "Purples")[5:8])
colors_dem = rev(brewer.pal(n = 8, name = "Blues")[5:8])
colors_rep = c("#700009", "#99000D", "#D80012", "#EF3B2C")

colors_grey = rev(brewer.pal(n = 8, name = "Greys")[5:8])
#show_col(colors_grey)

colors_parties2 = c("#2129B0", "#969696", "#BF1200")
colors_parties1 = c(colors_dem[1], colors_neutral[1], colors_rep[1])
colors_parties0 = c("#2129B0", "#3A084A", "#BF1200")
#show_col(colors_parties0)

#Display a Pallete
#show_col(colors_dem)

#Overwrite bbplot finalise_plot() function
source("bb_finalise_plot_academic.R")


dfb <- dfb %>% 
  filter(new_bm_party != "UNK") %>% 
  mutate(lnyear = log(year)) %>% 
  mutate(ticker_id = as.numeric(factor(ticker))) %>%
  mutate(lnticker = log(ticker_id)) %>% 
  mutate(lnage_med = log(age_median)) %>% 
  mutate(sector2 = fct_recode(sector,
    "Other"   = "Conglomerates",
    "Other"   = "Consumer Goods")) %>% 
  mutate(sector2 = factor(sector2))

```

```{r}
table(df$new_bm_party_dem)
```

```{r}
table(df$new_bm_party_rep)
```

```{r}
table(df$new_bm_party_unk)
```


```{r inspectsectors, eval=FALSE}

dfx <- dfb %>%
  filter(lag_years == 1) %>%
  select(ticker, sector) %>% 
  distinct()
  
table(dfx$sector)


dfx <- dfx %>% 
  mutate(sector2 = fct_recode(sector,
    "Other"   = "Conglomerates",
    "Other"   = "Consumer Goods")) %>% 
  mutate(sector2 = factor(sector2))


table(dfx$sector, dfx$sector2)
```



```{r}
df <- dfb %>%
  filter(lag_years == 1)

table(df$sector)


#TODO
#recode sector with 4cats, if sector has <1 firm, eg. recode

#y, boardparty med, cluster party, 
m1r <- glm(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median, 
              data = df, family = binomial(link = "logit"))



m2r <- glm(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                age_median +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median,
              data = df, family = binomial(link = "logit"))




m3r <- glm(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                age_median +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                sector,
              data = df, family = binomial(link = "logit"))


df <- dfb %>%
  filter(lag_years >= 1) 

m4r <- glm(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                age_median +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector + 
                lag_years,
              data = df, family = binomial(link = "logit"))


models <- list(m1r, m2r, m3r, m4r)

```


```{r maketable}
stargazer2(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001),
           font.size = "scriptsize",
           title = "Logit Models of Adding a New Board Member (Republican), Odds Ratios Displayed",
           dep.var.labels   = "New Board Member: Republican",
           covariate.labels = c("Board Member Swap", "Republican Board", "Amphibious Firm",
                               "Republican Firm", "Median Age",
                               "Proportion Female Board Members",
                               "Proportion Black or Hispanic Board Members",
                               "Proportion Minority Board Members",
                               "Proportion Non-US Board Members",
                               "Median Outside Board Ties",
                               "Sector: Capital Goods",
                               "Sector: Conglomerates",
                               "Sector: Consumer Cyclical",
                               "Sector: Consumer Goods",
                               "Sector: Consumer/Non-Cyclical",
                               "Sector: Energy",
                               "Sector: Financial",
                               "Sector: Healthcare",
                               "Sector: Services",
                               "Sector: Technology",
                               "Sector: Transportation",
                               "Sector: Utilities",
                               "Board Lag Years")
           
           
           
           )
```





```{r}
df <- dfb %>%
  filter(lag_years == 1) 


#TODO
#recode sector with 4cats, if sector has <1 firm, eg. recode

#y, boardparty med, cluster party, 
m1d <- glm(new_bm_party_dem ~ 
                board_change_events_list +
                bp_pid2n_median, 
              data = df, family = binomial(link = "logit"))



m2d <- glm(new_bm_party_dem ~ 
                board_change_events_list +
                bp_pid2n_median + 
                age_median +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median,
              data = df, family = binomial(link = "logit"))




m3d <- glm(new_bm_party_dem ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                age_median +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                sector,
              data = df, family = binomial(link = "logit"))


df <- dfb %>%
  filter(lag_years >= 1) 

m4d <- glm(new_bm_party_dem ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                age_median +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector + 
                lag_years,
              data = df, family = binomial(link = "logit"))


models <- list(m1d, m2d, m3d, m4d)

```


```{r}
stargazer2(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001),
           font.size = "scriptsize",
           title = "Logit Models of Adding a New Board Member (Democrat), Odds Ratios Displayed",
           dep.var.labels   = "New Board Member: Democrat",
           covariate.labels = c("Board Member Swap", "Republican Board", "Amphibious Firm",
                               "Republican Firm", "Median Age",
                               "Proportion Female Board Members",
                               "Proportion Black or Hispanic Board Members",
                               "Proportion Minority Board Members",
                               "Proportion Non-US Board Members",
                               "Median Outside Board Ties",
                               "Sector: Capital Goods",
                               "Sector: Conglomerates",
                               "Sector: Consumer Cyclical",
                               "Sector: Consumer Goods",
                               "Sector: Consumer/Non-Cyclical",
                               "Sector: Energy",
                               "Sector: Financial",
                               "Sector: Healthcare",
                               "Sector: Services",
                               "Sector: Technology",
                               "Sector: Transportation",
                               "Sector: Utilities",
                               "Board Lag Years")
           
           
           
           )
```





```{r testingmodels1, eval=FALSE}

df <- dfb %>%
  filter(lag_years < 3) 



#Random Slope for Year
#Random Slope for Ticker
#Crossed/Design or Multiple Membership
m1 <- glmer(new_bm_party_dem ~
              board_change_events_list +
              bp_pid2n_median +
              lag_years +
              (1|ticker) +
              (1|year) +
              (1|lag_years),
           data = df, family = binomial(link = "logit"))





#Tickers Nested in Years  (1|year/ticker)
#or equivalently (1|year) + (1|ticker:year)
m2 <- glmer(new_bm_party_dem ~
              board_change_events_list +
              bp_pid2n_median +
              lag_years +
              (1|year/ticker) +
              (1|lag_years),
           data = df, family = binomial(link = "logit"))

#Years nested in tickers
#use this method
m3 <- glmer(new_bm_party_dem ~
              board_change_events_list +
              bp_pid2n_median +
              lag_years +
              (1|ticker/year) +
              (1|lag_years),
           data = df, family = binomial(link = "logit"))


#Random Slope (BP) + Random Intercept Year
#+Random Intercept Ticker
# m4 <- glmer(new_bm_party_dem ~
#              board_change_events_list +
#              bp_pid2n_median +
#              ((1|year) + (0 + bp_pid2n_median | year)) +
#              (1|ticker),
#              #(1|year), 
#            data = df, family = binomial(link = "logit"))



models <- list(m1, m2, m3)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))
summary(m1)
summary(m2)
summary(m3)

#Compare Models
anova(m1, m2, m3) 
anova(m1, m3)

```


```{r testingmodels2, eval=FALSE}

df <- dfb %>%
  filter(lag_years < 3) 



#Random Slope for Year
#Random Slope for Ticker
#Crossed/Design or Multiple Membership
m1 <- glmer(new_bm_party_dem ~
              board_change_events_list +
              bp_pid2n_median +
              lag_years +
              (1|ticker) +
              (1|year),
           data = df, family = binomial(link = "logit"))





#Tickers Nested in Years  (1|year/ticker)
#or equivalently (1|year) + (1|ticker:year)
m2 <- glmer(new_bm_party_dem ~
              board_change_events_list +
              bp_pid2n_median +
              lag_years +
              (1|year/ticker),
           data = df, family = binomial(link = "logit"))

#************************
#Years nested in tickers
#use this method ****
#************************
m3 <- glmer(new_bm_party_dem ~
              board_change_events_list +
              bp_pid2n_median +
              lag_years +
              (1|ticker/year),
           data = df, family = binomial(link = "logit"))


#Random Slope (BP) + Random Intercept Year
#+Random Intercept Ticker
# m4 <- glmer(new_bm_party_dem ~
#              board_change_events_list +
#              bp_pid2n_median +
#              ((1|year) + (0 + bp_pid2n_median | year)) +
#              (1|ticker),
#              #(1|year), 
#            data = df, family = binomial(link = "logit"))



models <- list(m1, m2, m3)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))
summary(m1)
summary(m2)
summary(m3)

#Compare Models
anova(m1, m2, m3) 
anova(m1, m3)

```

```{r scrap, eval=FALSE}
df <- dfb %>%
  filter(lag_years == 1) 

# %>% 
#   select(year, lnyear, lnticker, ticker_id, ticker)



#TODO
#recode sector with 4cats, if sector has <1 firm, eg. recode

#Strategy, do two sets of tables
#one that has m1-m4, no lag years, for single lag year

#appendix can have differnt lag year slices

#another set of models, m1alr1 variants
#at different lag-year levels, 

#y, boardparty med, cluster party, 
m1lr <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              (1|ticker) +
              (1|year),
              # control=glmerControl(optimizer="bobyqa",
              #               optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))


m1lr1 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              (1|ticker/year),
              # control=glmerControl(optimizer="bobyqa",
              #               optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

anova(m1lr, m1lr1)



m1alr1 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              lag_years +
              (1|lnticker/lnyear),
              #(1|lag_years),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(m1alr1)

# m2lr <- glmer(new_bm_party_rep ~ 
#                 board_change_events_list +
#                 bp_pid2n_median + 
#                 #age_median +
#                 lnage_med +
#                 female_yes_mean +
#                 aa_hisp_yes_mean +            
#                 outside_public_boards_median +
#                 #lag_years +
#               (1|lag_years) +
#               # (1|lnticker/lnyear),
#               #(1|lnticker),
#               (1|lnyear),
#               data = df, family = binomial(link = "logit"))


m2lr <- glmer(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
              (1|lnticker) +
              (1|lnyear),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))



m2lr1 <- glmer(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                (1|lnticker/lnyear),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

anova(m2lr, m2lr1)

summary(m2lr1)

#breaks
# m3lr <- glmer(new_bm_party_rep ~ 
#                 board_change_events_list +
#                 bp_pid2n_median + 
#                 fec_cluster_party +
#                 lnage_med +
#                 female_yes_mean +
#                 minority_yes_mean +
#                 outside_public_boards_median +
#                 #sector +
#                 #(1|lag_years) +
#                 (1|lnticker/lnyear),
#                 #(1|lnyear),
#               data = df, family = binomial(link = "logit"))




m3lr <- glmer(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                sector +
                #(1|lag_years) +
                (1|lnticker) +
                (1|lnyear),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m3lr)


m3lr1 <- glmer(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                sector +
                #(1|lag_years) +
                #(1|lnticker) +
                (1|lnticker/lnyear),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m3lr1)


anova(m3lr, m3lr1)


# df <- dfb %>%
#   filter(lag_years <= 4) 
# 
# m4lr <- glmer(new_bm_party_rep ~ 
#                 board_change_events_list +
#                 bp_pid2n_median + 
#                 fec_cluster_party +
#                 age_median +
#                 female_yes_mean +
#                 aa_hisp_yes_mean +
#                 minority_yes_mean +
#                 non_usa_yes_mean +
#                 outside_public_boards_median +
#                 sector + 
#                 lag_years +
#                 (1|ticker/year),
#               data = df, family = binomial(link = "logit"))


models <- list(m1lr, m2lr, m3lr, m4lr)

```

# GLMER Models Full


```{r glmermodels_replag1}

df <- dfb %>%
  filter(lag_years == 1) 


m1lr <- glmer(new_bm_party_rep ~
        board_change_events_list +
              bp_pid2n_median +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(m1lr)
vif(m1lr)

m2lr <- glmer(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m2lr)
vif(m2lr)

m3lr <- glmer(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                #sector +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m3lr)
vif(m3lr)

m4lr <- glmer(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m4lr)
vif(m4lr)


#models <- list(m1lr, m2lr, m3lr, m4lr)
models <- list(m1lr, m2lr, m3lr, m4lr)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```

```{r glmermodels_demlag1}

df <- dfb %>%
  filter(lag_years == 1) 


m1ld <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(m1ld)
vif(m1ld)

m2ld <- glmer(new_bm_party_dem ~ 
                board_change_events_list +
                bp_pid2n_median + 
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m2ld)
vif(m2ld)

m3ld <- glmer(new_bm_party_dem ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                #sector +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m3ld)
vif(m3ld)

m4ld <- glmer(new_bm_party_dem ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m4ld)
vif(m4ld)

#models <- list(m1ld, m2ld, m3ld, m4ld)
models <- list(m1ld, m2ld, m3ld, m4ld)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```

```{r glmermodels_replag2}

df <- dfb %>%
  filter(lag_years == 2) 


m1lr2 <- glmer(new_bm_party_rep ~
        board_change_events_list +
              bp_pid2n_median +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(m1lr2)
vif(m1lr2)

m2lr2 <- glmer(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m2lr2)
vif(m2lr2)

m3lr2 <- glmer(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                #sector +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m3lr2)
vif(m3lr2)

m4lr2 <- glmer(new_bm_party_rep ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m4lr2)
vif(m4lr2)

#models <- list(m1lr, m2lr, m3lr, m4lr)
models <- list(m1lr2, m2lr2, m3lr2, m4lr2)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```

```{r glmermodels_demlag2}

df <- dfb %>%
  filter(lag_years == 2) 


m1ld2 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(m1ld2)
vif(m1ld2)

m2ld2 <- glmer(new_bm_party_dem ~ 
                board_change_events_list +
                bp_pid2n_median + 
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +            
                outside_public_boards_median +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m2ld2)
vif(m2ld2)

m3ld2 <- glmer(new_bm_party_dem ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                lnage_med +
                female_yes_mean +
                minority_yes_mean +
                outside_public_boards_median +
                #sector +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m3ld2)
vif(m3ld2)

m4ld2 <- glmer(new_bm_party_dem ~ 
                board_change_events_list +
                bp_pid2n_median + 
                fec_cluster_party +
                lnage_med +
                female_yes_mean +
                aa_hisp_yes_mean +
                minority_yes_mean +
                non_usa_yes_mean +
                outside_public_boards_median +
                sector +
                (1|ticker) +
                (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
              data = df, family = binomial(link = "logit"))

summary(m4ld2)
vif(m4ld2)

#models <- list(m1lr, m2lr, m3lr, m4lr)
models <- list(m1ld2, m2ld2, m3ld2, m4ld2)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))

```



#Tables of main coefficients, varying the number of included lag ranges

```{r, eval=FALSE}

df <- dfb %>%
  filter(lag_years <= 2)


mlr_2 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              lag_years +
              (1|lnticker/lnyear),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mlr_2)


df <- dfb %>%
  filter(lag_years <= 4)


mlr_4 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              lag_years +
              (1|lnticker/lnyear),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mlr_4)


df <- dfb %>%
  filter(lag_years <= 6)

mlr_6 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              lag_years +
              (1|lnticker/lnyear),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mlr_6)


df <- dfb %>%
  filter(lag_years <= 8)

mlr_8 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              lag_years +
              (1|lnticker/lnyear),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mlr_8)



models <- list(mlr_2, mlr_4, mlr_6, mlr_8)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))
```


```{r multilagmodels_dem}

df <- dfb %>%
  filter(lag_years <= 2)


mld_2 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              (1|lag_years) +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mld_2)
vif(mld_2)


df <- dfb %>%
  filter(lag_years <= 4)


mld_4 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              (1|lag_years) +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mld_4)
vif(mld_4)


df <- dfb %>%
  filter(lag_years <= 6)

mld_6 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              (1|lag_years) +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mld_6)
vif(mld_6)


df <- dfb %>%
  filter(lag_years <= 8)

mld_8 <- glmer(new_bm_party_dem ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              (1|lag_years) +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mld_8)
vif(mld_8)


models <- list(mld_2, mld_4, mld_6, mld_8)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))
```


```{r multilagmodels_rep}

df <- dfb %>%
  filter(lag_years <= 2)


mlr_2 <- glmer(new_bm_party_rep ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              (1|lag_years) +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mlr_2)
vif(mlr_2)


df <- dfb %>%
  filter(lag_years <= 4)


mlr_4 <- glmer(new_bm_party_rep ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              (1|lag_years) +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mlr_4)
vif(mlr_4)


df <- dfb %>%
  filter(lag_years <= 6)

mlr_6 <- glmer(new_bm_party_rep ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              (1|lag_years) +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mlr_6)
vif(mlr_6)


df <- dfb %>%
  filter(lag_years <= 8)

mlr_8 <- glmer(new_bm_party_rep ~
        board_change_events_list +
              bp_pid2n_median +
              fec_cluster_party +
              (1|lag_years) +
              (1|ticker) +
              (1|year),
              control=glmerControl(optimizer="bobyqa",
                            optCtrl=list(maxfun=2e5)),
        data = df, family = binomial(link = "logit"))

summary(mlr_8)
vif(mlr_8)


models <- list(mlr_2, mlr_4, mlr_6, mlr_8)

stargazer3(models,
           odd.ratio = T,
           type = "text",
           star.cutoffs = c(0.05, 0.01, 0.001))
```